BMLT Satellite Base Class: BMLTUTestPlugin Class Reference
BMLTUTestPlugin Class Reference
This is the class that implements and encapsulates the plugin functionality. * A single instance of this is created, and manages the plugin. *
This plugin registers errors by echoing HTML comments, so look at the source code of * the page if things aren't working right. *.
Public Member Functions
__construct ()
Constructor. *.
process_text ($in_string)
This uses the CMS text processor (t) to process the given string. *
This allows easier translation of displayed strings. All strings displayed by the * plugin should go through this function. * *.
admin_page ()
Presents the admin page. *.
standard_head ($in_text=null)
returns any necessary head content. *
admin_head ()
Returns any necessary head content for the admin. *.
Public Member Functions inherited from BMLTPlugin
adapt_to_lang ($in_lang="en")
Adapts all the static data members to the selected language. *.
& get_my_driver ()
Accessor: This gets the driver object. * *.
load_params ()
Loads the parameter list. *.
getBMLTOptions ($in_option_number=null)
This gets the admin options from the database. * *.
getBMLTOptions_by_id ($in_option_id, &$out_option_number=null)
This gets the admin options from the database, but by using the option id. * *.
setBMLTOptions ($in_options, $in_option_number=1)
This updates the database with the given options. * *.
getAdmin2Options ()
This gets the admin 2 options from the database. * *.
setAdmin2Options ($in_options)
This updates the database with the given options (Admin2 options). * *.
get_num_options ()
Gets the number of active options. * *.
make_new_options ()
Makes a new set of options, set as default. * *.
delete_options_by_id ($in_option_id)
Deletes the options by ID. * *.
delete_options ($in_option_number)
Deletes the indexed options. *
This is a bit of a delicate operation, because we need to re-index all of the other * options, beyond the one being deleted. *
You cannot delete the first options (1), if they are the only ones. * *.
process_admin_page (&$out_option_number)
This does any admin actions necessary. *.
return_admin_page ()
Returns the HTML for the admin page. * *.
display_options_sheet ($in_options_index=1, $display_mode='none')
This will return the HTML for one sheet of options in the admin page. * *.
bmlt_create_region_bias_select ($in_id, $in_options)
Creates the select element for the Region bias.
admin_ajax_handler ()
This does any admin actions necessary. *.
ajax_router ()
Handles some AJAX routes *
This function is called after the page has loaded its custom fields, so we can * figure out which settings we're using. If the settings support mobiles, and the UA * indicates this is a mobile phone, we redirect the user to our fast mobile handler. *.
content_filter ($in_the_content)
Massages the page content. * *.
display_quicksearch ($in_content)
This is a function that filters the content, and replaces a portion with the * "quick" search. * *.
display_popup_search ($in_content, $in_text, &$out_count)
This is a function that filters the content, and replaces a portion with the * "popup" search, if provided by the 'bmlt_simple_searches' custom field. * *.
display_bmlt_nouveau ($in_content)
This function implements the new, Maps API V. 3 version of the "classic" * BMLT search screen. * *.
display_simple_search ($in_content)
This is a function that filters the content, and replaces a portion with the * "simple" search * *.
display_table_search ($in_content)
This is a function that filters the content, and replaces a portion with the * new "table" search * *.
display_new_map_search ($in_content)
This is a function that filters the content, and replaces a portion with the * "new map" search * *.
BMLTPlugin_map_search_location_options ($in_options_id, $in_uid)
This returns a div of location options to be applied to the map search. * *.
BMLTPlugin_map_search_search_options ($in_options_id, $in_uid)
This returns a div of search options to be applied to the map search. * *.
BMLTPlugin_map_search_global_javascript_stuff ($in_options_id)
This returns the global JavaScript stuff for the new map search that only * only needs to be loaded once. * *.
BMLTPlugin_nouveau_map_search_global_javascript_stuff ($in_options_id)
This returns the global JavaScript stuff for the new map search that only * only needs to be loaded once. * *.
BMLTPlugin_map_search_local_javascript_stuff ($in_options_id, $in_uid)
This returns the JavaScript stuff that needs to be loaded into each of the * new map search instances. * *.
display_changes ($in_content)
This is a function that filters the content, and replaces a portion with the * "changes" dump. * *.
setup_one_change ($in_change_array, $in_single_uri=null)
Returns the XHTML for one single change record. * *.
BMLTPlugin_fast_mobile_lookup_javascript_stuff ()
Output the necessary Javascript. This is only called for a "pure javascript" * do_search invocation (smartphone interactive map). * *.
BMLTPlugin_fast_mobile_lookup_header_stuff ()
Output whatever header stuff is necessary for the available UA * *.
BMLTPlugin_draw_map_search_form ()
Returns the XHTML/WML for the Map Search form. These are the three "fast * lookup" links displayed at the top (Note display:none" in the style). * This is to be revealed by JavaScript. * *.
BMLTPlugin_draw_address_search_form ()
Returns the XHTML/WML for the Address Entry form * *.
BMLTPlugin_render_card ($ret, $index, $count, $meeting)
Renders one WML card * *.
BMLTPlugin_fast_mobile_lookup ()
Runs the lookup. * *.
Protected Member Functions
get_admin_ajax_base_uri ()
Return an HTTP path to the AJAX callback target. * *.
get_admin_form_uri ()
Return an HTTP path to the basic admin form submit (action) URI * *.
get_ajax_base_uri ()
Return an HTTP path to the AJAX callback target. * *.
get_plugin_path ()
Return an HTTP path to the plugin directory. * *.
cms_get_option ($in_option_key)
This gets the admin options from the database (allows CMS abstraction). * *.
cms_set_option ($in_option_key, $in_option_value)
This gets the admin options from the database (allows CMS abstraction). *.
cms_delete_option ($in_option_key)
Deletes a stored option (allows CMS abstraction). *.
cms_get_post_meta ($in_page_id, $in_settings_id)
This gets the page meta for the given page. (allows CMS abstraction). * *.
cms_get_page_settings_id ($in_text, $in_check_mobile=false)
This function fetches the settings ID for a page (if there is one). *
If $in_check_mobile is set to true, then ONLY a check for mobile support will be * made, and no other shortcodes will be checked. * *.
Protected Member Functions inherited from BMLTPlugin
geDefaultBMLTOptions ()
This gets the default admin options from the object (not the DB). * *.
set_callbacks ()
Sets up the admin and handler callbacks. Override this for your CMS. * NOTE: This may be ignored, but most CMSes have a system of callbacks, and * this function is a good place to establish those callbacks. * It is called at the end of the base class constructor. *.
get_ajax_mobile_base_uri ()
Return an HTTP path to the AJAX callback target for the mobile handler. * *.
Additional Inherited Members
Static Public Member Functions inherited from BMLTPlugin
static get_plugin_object ()
Get the instance * *.
static get_params ($in_array)
Loads a parameter list. * *.
static stripFile ($in_filename, $in_theme_dirname=null)
static mobile_sniff_ua ($in_http_vars)
Checks the UA of the caller, to see if it should return XHTML Strict or WML. *
NOTE: This is very, very basic. It is not meant to be a studly check, like WURFL. * *.
static get_shortcode ($in_text_to_parse, $in_code)
This will parse the given text, to see if it contains the submitted code. *
The code can be contained in EITHER an HTML comment (), OR a double-[[]] * notation. * *.
static replace_shortcode ($in_text_to_parse, $in_code, $in_replacement_text)
This will parse the given text, to see if it contains the submitted code. *
The code can be contained in EITHER an HTML comment (), OR a double-[[]] * notation. * *.
static BMLTPlugin_select_doctype ($in_http_vars)
Checks the UA of the caller, to see if it should return XHTML Strict or WML. *
NOTE: This is very, very basic. It is not meant to be a studly check, like WURFL. * *.
Public Attributes inherited from BMLTPlugin
$my_driver = null
This will contain an instance of the BMLT satellite driver class.
$my_params = null
This will contain the $this->my_http_vars and $_POST query variables.
$my_http_vars = null
This will hold all of the query arguments.
$my_table_next_id = 0
The next ID to use for the table.
$my_current_language
This contains whatever the current localization object is.
Static Public Attributes inherited from BMLTPlugin
static $g_s_there_can_only_be_one = null
This is a SINGLETON pattern. There can only be one...
static $adminOptionsName = "BMLTAdminOptions"
The name, in the database, for the version 1 options for this plugin.
static $admin2OptionsName = "BMLT2AdminOptions"
These options are for version 2.
static $default_rootserver = ''
This is the default root BMLT server URI.
static $default_map_center_latitude = 29.764377375163125
This is the default basic search map center latitude.
static $default_map_center_longitude = -95.4931640625
This is the default basic search map center longitude.
static $default_map_zoom = 8
This is the default basic search map zoom level.
static $default_details_map_zoom = 11
This is the default basic search map zoom level.
static $default_location_checked = 0
If nonzero, then the "This is a location" checkbox will be preselected.
static $default_location_services = 0
This tells the new default implementation whether or not location services should be available only for mobile devices.
static $default_gkey = ''
This is only necessary for older versions.
static $default_additional_css = ''
This is additional CSS that is inserted inline into the <head> section.
static $default_initial_view = ''
The initial view for old-style BMLT. It can be 'map', 'text', 'advanced', 'advanced map', 'advanced text' or ''.
static $default_theme = 'default'
This is the default for the "style theme" for the plugin. Different settings can have different themes.
static $default_language = 'en'
The default language is English, but the root server can override.
static $default_language_string = 'English'
The default language is English, and the name is spelled out, here.
static $default_distance_units = 'mi'
The default distance units are miles.
static $default_grace_period = 15
The default grace period for the mobile search (in minutes).
static $default_time_offset = 0
The default time offset from the main server (in hours).
static $default_military_time = false
If this is true, then time displays will be in military time.
static $default_startWeekday = 1
The default starting weekday (Sunday)
static $default_duration = '1:30'
The default duration of meetings.
static $default_geo_width = '-10'
The default geo width for searches.
static $local_options_success_time = 2000
The number of milliseconds a success message is displayed.
static $local_options_failure_time = 5000
The number of milliseconds a failure message is displayed.
Detailed Description
This is the class that implements and encapsulates the plugin functionality. * A single instance of this is created, and manages the plugin. *
This plugin registers errors by echoing HTML comments, so look at the source code of * the page if things aren't working right. *.
Definition at line 44 of file bmlt-unit-test-satellite-plugin.php.
Member Function Documentation
admin_page()
admin_page ()
Presents the admin page. *.
THE CMS CALLBACKS *
Definition at line 301 of file bmlt-unit-test-satellite-plugin.php.
     {
         echo $this->return_admin_page();
     }
References BMLTPlugin\return_admin_page().
cms_delete_option()
cms_delete_option ($in_option_key) protected
Deletes a stored option (allows CMS abstraction). *.
Parameters
$in_option_key The name of the option
Reimplemented from BMLTPlugin.
Definition at line 206 of file bmlt-unit-test-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         session_start();
         if (isset($_SESSION ['bmlt_settings'])) {
             $row = unserialize($_SESSION ['bmlt_settings']);
             if ($in_option_key != self::$admin2OptionsName) {
                 $index = max(1, intval(str_replace(self::$adminOptionsName . '_', '', $in_option_key)));
                 unset($row[$index - 1]);
                 $_SESSION ['bmlt_settings'] = serialize($row);
                 $ret = true;
             }
         }
         return $ret;
     }
cms_get_option()
cms_get_option ($in_option_key) protected
This gets the admin options from the database (allows CMS abstraction). * *.
Returns
an associative array, with the option settings. *
Parameters
$in_option_key The name of the option
Reimplemented from BMLTPlugin.
Definition at line 140 of file bmlt-unit-test-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         session_start();
         if (isset($_SESSION) && isset($_SESSION ['bmlt_settings'])) {
             $row = unserialize($_SESSION ['bmlt_settings']);
         } else {
             $row = array ( $this->geDefaultBMLTOptions() );
         }
         if ($in_option_key != self::$admin2OptionsName) {
             $index = max(1, intval(str_replace(self::$adminOptionsName . '_', '', $in_option_key)));
             $ret = isset($row[$index - 1]) ? $row[$index - 1] : $defaults[$index - 1];
         } else {
             $ret = array ( 'num_servers' => count($row) );
         }
         return $ret;
     }
References BMLTPlugin\geDefaultBMLTOptions().
cms_get_page_settings_id()
cms_get_page_settings_id ($in_text, $in_check_mobile = false) protected
This function fetches the settings ID for a page (if there is one). *
If $in_check_mobile is set to true, then ONLY a check for mobile support will be * made, and no other shortcodes will be checked. * *.
Returns
a mixed type, with the settings ID. *
Parameters
$in_text Required (for the base version) content to check.
$in_check_mobile True if this includes a check for mobile. Default is false.
Reimplemented from BMLTPlugin.
Definition at line 255 of file bmlt-unit-test-satellite-plugin.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $my_option_id = null;
         if (!$in_check_mobile && isset($this->my_http_vars['bmlt_settings_id']) && is_array($this->getBMLTOptions($this->my_http_vars['bmlt_settings_id']))) {
             $my_option_id = $this->my_http_vars['bmlt_settings_id'];
         } else {
             $support_mobile = self::get_shortcode($in_text, 'bmlt_mobile');
             if ($support_mobile === true) {
                 $options = $this->getBMLTOptions(1);
                 $support_mobile = strval($options['id']);
             }
             if ($in_check_mobile && $support_mobile && !isset($this->my_http_vars['BMLTPlugin_mobile']) && (self::mobile_sniff_ua($this->my_http_vars) != 'xhtml')) {
                 $my_option_id = $support_mobile;
             } elseif (!$in_check_mobile) {
                 if (isset($this->my_http_vars['bmlt_settings_id']) && intval($this->my_http_vars['bmlt_settings_id'])) {
                     $my_option_id = intval($this->my_http_vars['bmlt_settings_id']);
                 } elseif ($in_content = (isset($in_content) && $in_content) ? $in_content : $in_text) {
                     $my_option_id_content = parent::cms_get_page_settings_id($in_content, $in_check_mobile);
                     $my_option_id = $my_option_id_content ? $my_option_id_content : (isset($my_option_id) ? $my_option_id : null);
                 }
                 if (!isset($my_option_id) || !$my_option_id) {   // If nothing else gives, we go for the default (first) settings.
                     $options = $this->getBMLTOptions(1);
                     $my_option_id = $options['id'];
                 }
             }
         }
         return $my_option_id ;
     }
References BMLTPlugin\get_shortcode(), and BMLTPlugin\getBMLTOptions().
Referenced by standard_head().
cms_get_post_meta()
cms_get_post_meta ($in_page_id, $in_settings_id) protected
This gets the page meta for the given page. (allows CMS abstraction). * *.
Returns
a mixed type, with the meta data *
Parameters
$in_page_id The ID of the page/post
$in_settings_id The ID of the meta tag to fetch
Definition at line 236 of file bmlt-unit-test-satellite-plugin.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         return $ret;
     }
cms_set_option()
cms_set_option ($in_option_key, $in_option_value) protected
This gets the admin options from the database (allows CMS abstraction). *.
Parameters
$in_option_key The name of the option
$in_option_value the values to be set (associative array)
Reimplemented from BMLTPlugin.
Definition at line 168 of file bmlt-unit-test-satellite-plugin.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $index = 0;
         if ($in_option_key != self::$admin2OptionsName) {
             $index = max(1, intval(str_replace(self::$adminOptionsName . '_', '', $in_option_key)));
             session_start();
             if (isset($_SESSION) && isset($_SESSION ['bmlt_settings'])) {
                 $row_data = unserialize($_SESSION ['bmlt_settings']);
             } else {
                 $row_data = array ( $this->geDefaultBMLTOptions() );
             }
             if (isset($row_data) && is_array($row_data) && count($row_data)) {
                 $row_data[$index - 1] = $in_option_value;
                 unset($_SESSION ['bmlt_settings']);
                 $_SESSION ['bmlt_settings'] = serialize($row_data);
                 $ret = true;
             }
         } else {
             $ret = true; // Fake it, till you make it.
         }
         return $ret;
     }
References BMLTPlugin\geDefaultBMLTOptions().
get_admin_ajax_base_uri()
get_admin_ajax_base_uri () protected
Return an HTTP path to the AJAX callback target. * *.
Returns
a string, containing the path. *
Reimplemented from BMLTPlugin.
Definition at line 66 of file bmlt-unit-test-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->get_ajax_base_uri() . '?utest_string=admin';
     }
References get_ajax_base_uri().
Referenced by get_admin_form_uri().
get_admin_form_uri()
get_admin_form_uri () protected
Return an HTTP path to the basic admin form submit (action) URI * *.
Returns
a string, containing the path. *
Reimplemented from BMLTPlugin.
Definition at line 78 of file bmlt-unit-test-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->get_admin_ajax_base_uri();
     }
References get_admin_ajax_base_uri().
get_ajax_base_uri()
get_ajax_base_uri () protected
Return an HTTP path to the AJAX callback target. * *.
Returns
a string, containing the path. *
Reimplemented from BMLTPlugin.
Definition at line 90 of file bmlt-unit-test-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $port = $_SERVER['SERVER_PORT'] ;
         // IIS puts "off" in the HTTPS field, so we need to test for that.
         $https = (!empty($_SERVER['HTTPS']) && (($_SERVER['HTTPS'] !== 'off') || ($port == 443)));
         $server_path = $_SERVER['SERVER_NAME'];
         $my_path = $_SERVER['PHP_SELF'];
         $server_path .= trim((($https && ($port != 443)) || (!$https && ($port != 80))) ? ':' . $port : '', '/');
         $server_path = 'http' . ($https ? 's' : '') . '://' . $server_path . $my_path;
         return $server_path;
     }
Referenced by get_admin_ajax_base_uri(), and get_plugin_path().
get_plugin_path()
get_plugin_path () protected
Return an HTTP path to the plugin directory. * *.
Returns
a string, containing the path. *
Reimplemented from BMLTPlugin.
Definition at line 109 of file bmlt-unit-test-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = isset($this->my_http_vars['base_url']) ? $this->my_http_vars['base_url'] : dirname($this->get_ajax_base_uri()) . '/';
         return $ret;
     }
References get_ajax_base_uri().
Referenced by admin_head(), and standard_head().
process_text()
process_text ($in_string)
This uses the CMS text processor (t) to process the given string. *
This allows easier translation of displayed strings. All strings displayed by the * plugin should go through this function. * *.
Returns
a string, processed by WP. *
Parameters
$in_string The string to be processed.
Reimplemented from BMLTPlugin.
Definition at line 126 of file bmlt-unit-test-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $in_string = htmlspecialchars($in_string);
         return $in_string;
     }
standard_head()
standard_head ($in_text = null)
returns any necessary head content. *
Parameters
$in_text This is the page content text.
Definition at line 311 of file bmlt-unit-test-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->ajax_router();
         $load_head = false;   // This is a throwback. It prevents the GM JS from being loaded if there is no directly specified settings ID.
         $head_content = "<!-- Added by the BMLT plugin 3.0. -->\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\n<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\n<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
         $support_mobile = $this->cms_get_page_settings_id($in_text, true);
         if ($support_mobile) {
             $mobile_options = $this->getBMLTOptions_by_id($support_mobile);
         } else {
             $support_mobile = null;
         }
         $options = $this->getBMLTOptions_by_id($this->cms_get_page_settings_id($in_text));
         if ($support_mobile && is_array($mobile_options) && count($mobile_options)) {
             $mobile_url = $_SERVER['PHP_SELF'] . '?BMLTPlugin_mobile&bmlt_settings_id=' . $support_mobile;
             if (isset($this->my_http_vars['WML'])) {
                 $mobile_url .= '&WML=' . intval($this->my_http_vars['WML']);
             }
             if (isset($this->my_http_vars['simulate_smartphone'])) {
                 $mobile_url .= '&simulate_smartphone';
             }
             ob_end_clean();
             header("location: $mobile_url");
             die();
         }
         $this->my_http_vars['start_view'] = $options['bmlt_initial_view'];
         $this->load_params();
         $root_server_root = $options['root_server'];
         $url = $this->get_plugin_path();
         $head_content .= "\n" . '<style type="text/css">' . "\n";
         $temp = self::stripFile('styles.css', $options['theme']);
         if ($temp) {
             $image_dir_path = $this->get_plugin_path() . '/themes/' . $options['theme'] . '/images/';
             $temp = str_replace('##-IMAGEDIR-##', $image_dir_path, $temp);
             $head_content .= "\t$temp\n";
         }
         $temp = self::stripFile('nouveau_map_styles.css', $options['theme']);
         if ($temp) {
             $image_dir_path = $this->get_plugin_path() . '/themes/' . $options['theme'] . '/images/';
             $temp = str_replace('##-IMAGEDIR-##', $image_dir_path, $temp);
             $head_content .= "\t$temp\n";
         }
         $head_content .= self::stripFile('table_styles.css') . "\n";
         $head_content .= self::stripFile('quicksearch.css') . "\n";
         $dirname = dirname(__FILE__) . '/themes';
         $dir = new DirectoryIterator($dirname);
         foreach ($dir as $fileinfo) {
             if (!$fileinfo->isDot()) {
                 $fName = $fileinfo->getFilename();
                 $temp = self::stripFile("table_styles.css", $fName);
                 if ($temp) {
                     $image_dir_path = $this->get_plugin_path() . '/themes/' . $fName . '/images/';
                     $temp = str_replace('##-IMAGEDIR-##', $image_dir_path, $temp);
                     $head_content .= "\t$temp\n";
                 }
                 $temp = self::stripFile("quicksearch.css", $fName);
                 if ($temp) {
                     $head_content .= "\t$temp\n";
                 }
             }
         }
         $head_content .= '</style>';
         $head_content .= "\n" . '<style type="text/css">' . "\n";
         $head_content .= "\n/* Responsiveness */\n";
         $head_content .= self::stripFile('responsiveness.css');
         $head_content .= '</style>' . "\n";
         if ($root_server_root) {
             $root_server = $root_server_root . "/client_interface/xhtml/index.php";
             $additional_css = '.bmlt_container * {margin:0;padding:0;text-align:center }';
             if ($options['additional_css']) {
                 $additional_css .= $options['additional_css'];
             }
             if ($additional_css) {
                 $head_content .= '<style type="text/css">' . preg_replace("|\s+|", " ", $additional_css) . '</style>';
             }
         }
         $head_content .= '<script type="text/javascript">';
         $head_content .= self::stripFile('javascript.js');
         if ($this->get_shortcode($in_text, 'bmlt_quicksearch')) {
             $head_content .= self::stripFile('quicksearch.js') . (defined('_DEBUG_MODE_') ? "\n" : '');
         }
         if ($this->get_shortcode($in_text, 'bmlt_map')) {
             $head_content .= self::stripFile('map_search.js');
         }
         if ($this->get_shortcode($in_text, 'bmlt_mobile')) {
             $head_content .= self::stripFile('fast_mobile_lookup.js');
         }
         $head_content .= '</script>';
         return $head_content;
     }
References BMLTPlugin\ajax_router(), cms_get_page_settings_id(), get_plugin_path(), BMLTPlugin\getBMLTOptions_by_id(), BMLTPlugin\load_params(), and BMLTPlugin\stripFile().
Referenced by admin_head().
The documentation for this class was generated from the following file:
/home/runner/work/bmlt-satellite-base-class/bmlt-satellite-base-class/bmlt-unit-test-satellite-plugin.php