BMLT Satellite Base Class: /home/travis/build/bmlt-enabled/bmlt-satellite-base-class/admin_javascript.js File Reference
/home/travis/build/bmlt-enabled/bmlt-satellite-base-class/admin_javascript.js File Reference
The javascript for the BMLTPlugin class (Admin options). *.
Functions
function BMLTPlugin_GetSelectedOptionIndex ()
Returns the selected option index. * *.
function BMLTPlugin_ClickInText (in_id, in_default_text, in_blur)
Hides "primer" text in text items. *.
function BMLTPlugin_SelectOptionSheet (in_value, in_num_options)
Switches the visibility of the property sheets -called when the select changes. *.
function BMLTPlugin_DeleteOptionSheet ()
Deletes one of the options after a confirm. *.
function BMLTPlugin_PropagateAPIKey (in_key_value)
This spreads a new Google API Key to all options. *.
function BMLTPlugin_SaveOptions ()
This actually saves the new options. *.
function BMLTPlugin_SettingCallback (in_success)
AJAX callback for the settings. *.
function BMLTPlugin_DirtifyOptionSheet (in_disable)
When a change is made to an option, this sets a "dirty" flag, by enabling the * "Save Changes" button. *.
function BMLTPlugin_CloseHandler ()
Puts up an "are you sure?" message if the dirty flag is set. * *.
function BMLTPlugin_StartFader ()
Starts the message "fader." *
Simple fader, taken from here: * http://www.switchonthecode.com/tutorials/javascript-tutorial-simple-fade-animation *.
function BMLTPlugin_animateFade (lastTick, eid)
Animates the fade. *
Simple fader, taken from here: * http://www.switchonthecode.com/tutorials/javascript-tutorial-simple-fade-animation *.
function BMLTPlugin_TestRootUri_call ()
Uses AJAX to test the given root server URI. *.
function BMLTPlugin_TestRootUriCallback (in_success)
Uses AJAX to test the given root server URI. *.
function BMLTPlugin_admin_load_map ()
Load the map and set it up. *.
google maps event addListener (g_BMLTPlugin_admin_main_map,"click", function(in_event){g_BMLTPlugin_admin_marker.setPosition(in_event.latLng);BMLTPlugin_admin_MovedMarker();})
g_BMLTPlugin_admin_main_map panTo (new google.maps.LatLng(latitude, longitude))
g_BMLTPlugin_admin_main_map setZoom (zoom)
BMLTPlugin_admin_CreateMarker ()
Create a generic marker. *.
function BMLTPlugin_admin_MovedMarker ()
Create a generic marker. * *.
Variables
var g_BMLTPlugin_admin_main_map = null
This will hold the map instance.
var g_BMLTPlugin_admin_marker = null
This holds the marker object.
var g_BMLTPlugin_AjaxRequest = null
Used to stop server checks from stepping on each other.
var g_BMLTPlugin_oldBeforeUnload = null
We replace the window's beforeUnload with our prompt.
var g_BMLTPlugin_hold_the_pickles = false
This is set to avoid dirtifying the sheet.
else
Detailed Description
The javascript for the BMLTPlugin class (Admin options). *.
This file is part of the BMLT Common Satellite Base Class Project. The project GitHub page is available here: https://github.com/MAGSHARE/BMLT-Common-CMS-Plugin-Class
This file is part of the Basic Meeting List Toolbox (BMLT).
Find out more at: https://bmlt.app
BMLT is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
BMLT is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this code. If not, see http://www.gnu.org/licenses/.
Definition in file admin_javascript.js.
Function Documentation
function BMLTPlugin_admin_CreateMarker ()
Create a generic marker. *.
These describe the "You are here" icon.
Definition at line 533 of file admin_javascript.js.
References BMLTPlugin_admin_MovedMarker(), BMLTPlugin_GetSelectedOptionIndex(), g_BMLTPlugin_admin_main_map, and g_BMLTPlugin_admin_marker.
Referenced by BMLTPlugin_admin_load_map().
 {
     /// These describe the "You are here" icon.
     var center_icon_image = new google.maps.MarkerImage ( c_g_BMLTPlugin_admin_google_map_images+'/NACenterMarker.png', new google.maps.Size(21, 36), new google.maps.Point(0,0), new google.maps.Point(11, 36) );
     var center_icon_shadow = new google.maps.MarkerImage( c_g_BMLTPlugin_admin_google_map_images+'/NACenterMarkerS.png', new google.maps.Size(43, 36), new google.maps.Point(0,0), new google.maps.Point(11, 36) );
     var center_icon_shape = { coord: [16,0,18,1,19,2,19,3,20,4,20,5,20,6,20,7,20,8,20,9,20,10,20,11,19,12,17,13,16,14,16,15,15,16,15,17,14,18,14,19,13,20,13,21,13,22,13,23,12,24,12,25,12,26,12,27,11,28,11,29,11,30,11,31,11,32,11,33,11,34,11,35,10,35,10,34,9,33,9,32,9,31,9,30,9,29,9,28,8,27,8,26,8,25,8,24,8,23,7,22,7,21,7,20,6,19,6,18,5,17,5,16,4,15,4,14,3,13,1,12,0,11,0,10,0,9,0,8,0,7,0,6,0,5,0,4,1,3,1,2,3,1,4,0,16,0], type: 'poly' };
     if ( g_BMLTPlugin_admin_marker )
         {
         g_BMLTPlugin_admin_marker.setMap( null );
         g_BMLTPlugin_admin_marker = null;
         }
     var option_index = BMLTPlugin_GetSelectedOptionIndex();
     var longitude = parseFloat ( c_g_BMLTPlugin_coords[option_index-1].lng );
     var latitude = parseFloat ( c_g_BMLTPlugin_coords[option_index-1].lat );
     g_BMLTPlugin_admin_marker = new google.maps.Marker ( { 'position':      new google.maps.LatLng ( latitude, longitude ),
                                                             'map':          g_BMLTPlugin_admin_main_map,
                                                             'shadow':       center_icon_shadow,
                                                             'icon':         center_icon_image,
                                                             'shape':        center_icon_shape,
                                                             'draggable':    true
                                                             } );
     if ( g_BMLTPlugin_admin_marker )
         {
         google.maps.event.addListener ( g_BMLTPlugin_admin_marker, "dragend", BMLTPlugin_admin_MovedMarker );
         };
 };
function BMLTPlugin_admin_MovedMarker ()
Create a generic marker. * *.
Returns
a marker object. *
Definition at line 568 of file admin_javascript.js.
References BMLTPlugin_DirtifyOptionSheet(), BMLTPlugin_GetSelectedOptionIndex(), g_BMLTPlugin_admin_main_map, and g_BMLTPlugin_admin_marker.
Referenced by BMLTPlugin_admin_CreateMarker(), and BMLTPlugin_admin_load_map().
 {
     var option_index = BMLTPlugin_GetSelectedOptionIndex();
     BMLTPlugin_DirtifyOptionSheet();
     c_g_BMLTPlugin_coords[option_index-1].lat = g_BMLTPlugin_admin_marker.getPosition().lat();
     c_g_BMLTPlugin_coords[option_index-1].lng = g_BMLTPlugin_admin_marker.getPosition().lng();
     c_g_BMLTPlugin_coords[option_index-1].zoom = g_BMLTPlugin_admin_main_map.getZoom();
     g_BMLTPlugin_admin_main_map.panTo ( g_BMLTPlugin_admin_marker.getPosition() );
 }
function BMLTPlugin_animateFade (lastTick, eid)
Animates the fade. *
Simple fader, taken from here: * http://www.switchonthecode.com/tutorials/javascript-tutorial-simple-fade-animation *.
Parameters
lastTick The time of the last tick.
eid The element ID
Definition at line 410 of file admin_javascript.js.
 {
     var curTick = new Date().getTime();
     var elapsedTicks = curTick - lastTick;
     var element = document.getElementById ( eid );
     if ( element.FadeTimeLeft <= elapsedTicks )
         {
         element.style.opacity = element.FadeState == 1 ? '1' : '0';
         element.style.filter = 'alpha(opacity = ' + (element.FadeState == 1 ? '100' : '0') + ')';
         element.FadeState = element.FadeState == 1 ? 2 : -2;
         return;
         };
     element.FadeTimeLeft -= elapsedTicks;
     var newOpVal = element.FadeTimeLeft/g_BMLTPlugin_TimeToFade;
     if ( element.FadeState == 1 )
         {
         newOpVal = 1 - newOpVal;
         };
     element.style.opacity = newOpVal;
     element.style.filter = 'alpha(opacity = ' + (newOpVal*100) + ')';
     setTimeout ( "BMLTPlugin_animateFade(" + curTick + ",'" + eid + "')", 33 );
 };
function BMLTPlugin_ClickInText (in_id, in_default_text, in_blur)
Hides "primer" text in text items. *.
Parameters
in_id The ID of the item
in_default_text The "primer" text.
in_blur If this is true, then we reverse the process.
Definition at line 52 of file admin_javascript.js.
Referenced by BMLTPlugin::display_options_sheet().
 {
     var item = document.getElementById(in_id);
     if ( item && (item.type == 'text') )
         {
         var value = item.value.toString();
         if ( (in_blur != true) && value && (value == in_default_text) )
             {
             item.value = '';
             }
         else
             {
             if ( (in_blur == true) && !value )
                 {
                 item.value = in_default_text;
                 };
             };
         };
 }
function BMLTPlugin_DirtifyOptionSheet (in_disable)
When a change is made to an option, this sets a "dirty" flag, by enabling the * "Save Changes" button. *.
Parameters
in_disable If this is true, then we "clean" the flag.
Definition at line 320 of file admin_javascript.js.
References BMLTPlugin_CloseHandler(), and g_BMLTPlugin_oldBeforeUnload.
Referenced by BMLTPlugin_admin_load_map(), BMLTPlugin_admin_MovedMarker(), BMLTPlugin_SettingCallback(), and BMLTPlugin::display_options_sheet().
 {
     var keyID = (window.event && window.event.keyCode) ? window.event.keyCode : null;
     if ( keyID != 9 )   // Don't react to tab.
         {
         document.getElementById ( 'BMLTPlugin_toolbar_button_save' ).disabled = (in_disable == true);
         document.getElementById ( 'BMLTPlugin_toolbar_button_save' ).className = 'BMLTPlugin_toolbar_button_save_' + ((in_disable == true) ? 'disabled' : 'enabled').toString();
         document.getElementById ( 'BMLTPlugin_toolbar_button_new' ).disabled = (in_disable != true);
         document.getElementById ( 'BMLTPlugin_toolbar_button_new' ).className = ((in_disable != true) ? 'BMLTPlugin_toolbar_button_save_disabled' : 'BMLTPlugin_create_button').toString();
         if ( document.getElementById ( 'BMLTPlugin_toolbar_button_del' ) )
             {
             document.getElementById ( 'BMLTPlugin_toolbar_button_del' ).disabled = (in_disable != true);
             document.getElementById ( 'BMLTPlugin_toolbar_button_del' ).className = ((in_disable != true) ? 'BMLTPlugin_toolbar_button_save_disabled' : 'BMLTPlugin_delete_button').toString();
             };
         if ( !document.getElementById ( 'BMLTPlugin_toolbar_button_save' ).disabled )
             {
             if ( window.onbeforeunload != BMLTPlugin_CloseHandler )
                 {
                 g_BMLTPlugin_oldBeforeUnload = window.onbeforeunload;
                 window.onbeforeunload = BMLTPlugin_CloseHandler;
                 };
             }
         else
             {
             window.onbeforeunload = g_BMLTPlugin_oldBeforeUnload;
             };
         };
 };
function BMLTPlugin_GetSelectedOptionIndex ()
Returns the selected option index. * *.
Returns
an integer. *
Definition at line 37 of file admin_javascript.js.
Referenced by BMLTPlugin_admin_CreateMarker(), BMLTPlugin_admin_load_map(), BMLTPlugin_admin_MovedMarker(), BMLTPlugin_DeleteOptionSheet(), BMLTPlugin_TestRootUri_call(), and BMLTPlugin_TestRootUriCallback().
 {
     var option_select = document.getElementById ( 'BMLTPlugin_legend_select' );
     var option_index = 1;
     if ( option_select )
         {
         option_index = parseInt ( option_select.value );
         }
     return option_index;
 }
function BMLTPlugin_PropagateAPIKey (in_key_value)
This spreads a new Google API Key to all options. *.
Parameters
in_key_value The value of the API Key to spread.
Definition at line 122 of file admin_javascript.js.
Referenced by BMLTPlugin::display_options_sheet().
 {
     for ( var option_index = 1; option_index <= c_g_BMLTPlugin_coords.length; option_index++ )
         {
         var apiKeyTextObject = document.getElementById ( 'BMLTPlugin_google_api_text_'+option_index );
         if ( apiKeyTextObject )
             {
             apiKeyTextObject.value = in_key_value;
             };
         };
 };
function BMLTPlugin_SelectOptionSheet (in_value, in_num_options)
Switches the visibility of the property sheets -called when the select changes. *.
Parameters
in_value The current value of the select
in_num_options The number of available options.
Definition at line 80 of file admin_javascript.js.
References BMLTPlugin_admin_load_map().
 {
     for ( var i=1; i<=in_num_options; i++ )
         {
         var item_id = 'BMLTPlugin_option_sheet_'+i+'_div';
         var item = document.getElementById(item_id);
         if ( item )
             {
             item.style.display = ((i == in_value) ? 'block' : 'none');
             };
         };
     BMLTPlugin_admin_load_map();
     var indicator = document.getElementById ( 'BMLTPlugin_option_sheet_indicator_'+in_value );
     var version = document.getElementById ('BMLTPlugin_option_sheet_version_indicator_'+in_value );
     indicator.className = 'BMLTPlugin_option_sheet_NEUT';
     version.innerHTML = null;
 };
function BMLTPlugin_SettingCallback (in_success)
AJAX callback for the settings. *.
Parameters
in_success The HTTPRequest object
Definition at line 273 of file admin_javascript.js.
References BMLTPlugin_DirtifyOptionSheet(), and BMLTPlugin_StartFader().
Referenced by BMLTPlugin_SaveOptions().
 {
     var fader = document.getElementById ( 'BMLTPlugin_Fader' );
     if ( fader )
         {
         fader.style.opacity = 1;
         fader.FadeState = null;
         if ( parseInt(in_success.responseText) != 1 )
             {
             fader.innerHTML = c_g_BMLTPlugin_failure_message;
             fader.className = 'BMLTPlugin_Message_bar_fail';
             g_BMLTPlugin_TimeToFade = c_g_BMLTPlugin_failure_time;
             }
         else
             {
             fader.innerHTML = c_g_BMLTPlugin_success_message;
             fader.className = 'BMLTPlugin_Message_bar_success';
             g_BMLTPlugin_TimeToFade = c_g_BMLTPlugin_success_time;
             BMLTPlugin_DirtifyOptionSheet ( true );
             for ( var option_index = 1; option_index <= c_g_BMLTPlugin_coords.length; option_index++ )
                 {
                 var name = document.getElementById ( 'BMLTPlugin_option_sheet_name_'+option_index ).value.toString();
                 if ( name && (name != c_g_BMLTPlugin_no_name) )
                     {
                     var option = document.getElementById ( 'BMLTPlugin_option_sel_'+option_index );
                     if ( !option )
{
                         option = document.getElementById ( 'BMLTPlugin_legend' );
                         };
                     option.innerHTML = name;
                     };
                 };
             };
         BMLTPlugin_StartFader();
         };
 };
function BMLTPlugin_TestRootUriCallback (in_success)
Uses AJAX to test the given root server URI. *.
Parameters
in_success The text in this is either 1 or 0
Definition at line 473 of file admin_javascript.js.
References BMLTPlugin_GetSelectedOptionIndex().
Referenced by BMLTPlugin_TestRootUri_call().
 {
     var option_index = BMLTPlugin_GetSelectedOptionIndex();
     var indicator = document.getElementById ( 'BMLTPlugin_option_sheet_indicator_'+option_index );
     var version = document.getElementById ('BMLTPlugin_option_sheet_version_indicator_'+option_index );
     if ( !in_success.responseText || (parseInt(in_success.responseText) == 0) )
         {
         indicator.className = 'BMLTPlugin_option_sheet_BAD';
         version.innerHTML = c_g_BMLTPlugin_test_server_failure;
         }
     else
         {
         indicator.className = 'BMLTPlugin_option_sheet_OK';
         version.innerHTML = c_g_BMLTPlugin_test_server_success+in_success.responseText;
         };
 };
Variable Documentation
else
Initial value:
{
        g_BMLTPlugin_hold_the_pickles = true
Definition at line 520 of file admin_javascript.js.